language: nodejs
cache:
    directories:
        - node_modules
        - ~/.npm       
node_js:
    - '12'
git:
    depth: 3
notifications:
    email:
        recipients:
            - luis_rdz5@hotmail.com
            - luis@luisrodriguezgarcia.com
        on_success: always
        on_failure: always
deploy:
    provide: heroku
    skip-cleanup: true
    keep-history: true
    api_key: abcbee53-d42e-4e8d-972d-dadb6ad2bd8a
    app: destcar_backend
    on:
        repo: luisrdz5/destcar_backend